server:
  port: 8081
  error:
    include-message: always

spring:
  flyway:
    enabled: true
    baselineVersion: 1
    locations:
      - classpath:db/migration
    sqlMigrationSuffixes: .sql
    baselineOnMigrate: true
    sqlMigrationPrefix: V
    schemas: public

  datasource:
    url: jdbc:postgresql://ruby.db.elephantsql.com:5432/mdqpohhv?socketTimeout=3
    username: mdqpohhv
    password: j_auuReXMWVRkFtAQN1i3peeUfwo_piR
    driverClassName: org.postgresql.Driver
