server:
  port: 8081
  error:
    include-message: always
#Configuracion de spring
spring:
  #Configuracion de migracion
  flyway:
    enabled: true
    baselineVersion: 1
    locations:
      classpath: db/migration
    sqlMigrationSuffixes: .sql
    baselineOnMigrate: true
    sqlMigrationPrefix: V
    schemas: public

  datasource:
    url: jdbc:postgresql://mdancxxn:***@lallah.db.elephantsql.com:5432/mdancxxn?socketTimeout=3
    username: mdancxxn
    password: bdtLf5Y7y-ubfEwRBh_gk6s_cVR6CB2J
    driverClassName: org.postgresql.Driver