server:
  port: 8080
  error:
    include-message: always
#Configuracion de spring
spring:
  #Configuracion de migracion
  flyway:
    enabled: true
    baselineVersion: 1
    locations:
      classpath: db/migration
    sqlMigrationSuffixes: .sql
    baselineOnMigrate: true
    sqlMigrationPrefix: V
    schemas: public

  datasource:
    url: jdbc:postgresql://faheagix:***@stampy.db.elephantsql.com:5432/faheagix?socketTimeout=3
    username: faheagix
    password: postgres://faheagix:erYa_qvYVxDl5oGD6lWx9hEh-vK3VhDu@stampy.db.elephantsql.com/faheagix
    driverClassName: org.postgresql.Driver